// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_economy.sql

package db

import (
	"context"
)

const getUserBalanceByUserId = `-- name: GetUserBalanceByUserId :one
SELECT user_id, balance, isfreeze, id FROM user_economy WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetUserBalanceByUserId(ctx context.Context, userID int32) (UserEconomy, error) {
	row := q.queryRow(ctx, q.getUserBalanceByUserIdStmt, getUserBalanceByUserId, userID)
	var i UserEconomy
	err := row.Scan(
		&i.UserID,
		&i.Balance,
		&i.Isfreeze,
		&i.ID,
	)
	return i, err
}
