// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package db

import (
	"context"
)

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT email, username, password, isadmin, ip, uuid, accesstoken, serverid, reg_data, last_login_site, id FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUserName(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUserNameStmt, getUserByUserName, username)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Isadmin,
		&i.Ip,
		&i.Uuid,
		&i.Accesstoken,
		&i.Serverid,
		&i.RegData,
		&i.LastLoginSite,
		&i.ID,
	)
	return i, err
}
